package Streams.Homeworks;

public enum Subject {
    MATH, GERMAN, ENGLISH, FRENCH, CHEMISTRY, PHYSICS, BIOLOGY, HISTORY, GEOGRAPHY, COMPUTER_SCIENCE, SPORTS, ART, MUSIC, RELIGION, POLITICS, ECONOMICS, PHILOSOPHY, PSYCHOLOGY, SOCIOLOGY, LATIN, GREEK, CHINESE, RUSSIAN, JAPANESE
}
